config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"

  get '/users/most-active' => 'users#most_active'

  get '/categories' => 'categories#index'
 
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
 
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
 
  delete '/logout' => 'sessions#destroy'

  get "/auth/:provider/callback" => 'sessions#google'

  resources :jobs do
    resources :reviews
  end

  resources :reviews
  resources :users do
    resources :jobs, shallow: true
  end

  resources :categories, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :jobs
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :reviews
  has_many :users, through: :reviews
  validates :content, :title, presence: true

  scope :alpha, -> { order(:title) }
  scope :most_reviews, -> { left_joins(:reviews).group('jobs.id').order('count(reviews.job_id) desc') }

  def category_attributes=(attr)
    self.category = Category.find_or_create_by(attr) if !attr[:name].blank?
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :job

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :jobs
    has_many :reviews
    has_many :reviewed_jobs, through: :reviews, source: :job
    has_secure_password
    has_many :categories, through: :jobs

    validates :username, :email, presence: true
    validates :username, uniqueness: {scope: :username, message: "already exists"}

    def self.most_active
        @top_users = joins(:jobs).group(:user_id).order("count(user_id) desc").limit(3)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    helper_method :current_user, :logged_in?
   
    private
     def current_user
      @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
     end
  
     def logged_in?
       !!session[:user_id]
     end
  
     def redirect_if_not_logged_in
        redirect_to '/' if !logged_in?
     end  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    def index
        @categories = Category.all.includes(:jobs)
    end

    def show
        @category = Category.find_by_id(params[:id])
    end

    def new
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    before_action :redirect_if_not_logged_in

    def new
        if params[:user_id] && @user = User.find_by_id(params[:user_id])
            @job = @user.jobs.build
        else
            @job = Job.new
        end
        @job.build_category
    end

    def index
        if params[:user_id] && @user = User.find_by_id(params[:user_id])
            @jobs = @user.jobs.alpha
        else
            @error = "That user doesn't exist" if params[:user_id]
            @jobs = Job.alpha.includes(:category, :user)
        end
    end

    def create
        @job = current_user.jobs.build(job_params)
        if @job.save
            redirect_to jobs_path
        else
            render :new
        end
    end

    def edit
        @job = Job.find_by_id(params[:id])
        redirect_to jobs_path if !@job || @job.user != current_user
        @job.build_category if !@job.category
    end

    def update
        @job = Job.find_by(id: params[:id])
        redirect_to jobs_path if !@job || @job.user != current_user
        if @job.update(job_params)
            redirect_to job_path(@job)
        else
            render :edit
        end
    end

    def show
        @job = Job.find_by_id(params[:id])
        redirect_to jobs_path if !@job
    end

    def destroy
        @job = Job.find(params[:id])
        @job.destroy
        redirect_to jobs_path
    end

    private

    def job_params
         params.require(:job).permit(:title, :company, :content, :category_id, category_attributes: [:name])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :set_review, only: [:show, :edit, :update]
    before_action :redirect_if_not_review_author, only: [:edit, :update]

    def index
        if params[:job_id] && @job = Job.find_by_id(params[:job_id])
            @reviews = @job.reviews
        else
            @error = "That job doesn't exist" if params[:job_id]
            @reviews = Review.all
        end
    end

    def new
        if params[:job_id] && @job = Job.find_by_id(params[:job_id])
            @review = @job.reviews.build
        else
            @error = "That job doesn't exist" if params[:job_id]
            @review = Review.new
        end
    end

    def create
        @review = current_user.reviews.build(review_params)
        if @review.save
            redirect_to reviews_path
        else
            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
        if @review.update(review_params)
            redirect_to review_path(@review)
        else
            render :edit
        end
    end

    def destroy
        @review = Review.find(params[:id])
        @review.destroy
        redirect_to reviews_path
    end

    private

    def review_params 
        params.require(:review).permit(:content, :job_id)
    end

    def set_review
        @review = Review.find_by(id: params[:id])
        if !@review
            flash[:message] = "Review was not found"
            redirect_to reviews_path
        end
    end

    def redirect_if_not_review_author
        redirect_to reviews_path if @review.user != current_user
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def destroy
        session.clear
        redirect_to root_path
    end

    def create
        user = User.find_by(username: params[:user][:username])
        if user && user.authenticate(params[:user][:password])
            session[:user_id] = user.id
            redirect_to user_path(user)
        else
            flash[:message] = "Incorrect login info, please try again."
            redirect_to "/login"
        end
    end

    def google
        @user = User.find_or_create_by(email: auth["info"]["email"]) do |user|
          user.username = auth["info"]["first_name"]
          user.password = SecureRandom.hex(10)
        end
        if @user.save
          session[:user_id] = @user.id
          redirect_to user_path(@user)
        else
          redirect_to '/'
        end
    end

    private

    def auth
        request.env['omniauth.auth']
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to @user
        else
            render :new
        end
    end

    def show
        redirect_if_not_logged_in
        @user = User.includes(jobs: :category).find_by_id(params[:id])
        redirect_to '/' if !@user
    end

    def most_active
        @top_users = User.most_active
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
    def index_display_header
        if @user
            "#{@user.username}'s Jobs:"
        else
            "All Jobs"
        end
    end

    def display_jobs
        if @user.jobs.empty?
            tag.h2(link_to("No jobs yet - Create a job Here", new_job_path))
        else
            content_tag(:h2, "Your Jobs:")
            render partial: "jobs/jobs", locals: {jobs: @user.jobs}
            # user = @user == current_user ? 'Your' : "#{@user.username}'s"
            # content_tag(:h2, "#{user} #{pluralize(@user.jobs.count, 'Job')}:")
        end
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb
<ul>
  <% @categories.each do |category| %>
    <li>
      <h1><%= category.name %></h1>
      <ul>
        <% category.jobs.each do  |job| %>
          <li><%= link_to job.title, job_path(job)  %></li>
        <% end  %>
      </ul>
    </li>
  <% end %>
</ul>

app/views/categories/show.html.erb
<h1><%= @category.name %> - <%= pluralize(@category.jobs.count, "jobs") %></h1>

<ol>
    <% @category.jobs.each do  |job| %>
      <li><%= link_to job.title, job_path(job)  %></li>
    <% end  %>
</ol>

app/views/jobs/_jobs.html.erb
<ul>
    <% jobs.each do |j|%>
      <li><%= link_to j.title, job_path(j) %></li>
    <% end %>
</ul>

app/views/jobs/edit.html.erb
<h1>Edit <%= @job.title%>!</h1>

<%= render partial: "layouts/errors", locals: {object: @job} %>

<%= form_for(@job) do |f|%>
    <%= f.label "Choose a category:" %>
    <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: true %>


    <p>Or create a new category:
    <%= f.fields_for :category do |c|%>
        <%= c.text_field :name%>
    <% end %>
    </p>

    <br>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <%= f.label :company %>
    <%= f.text_field :company %>
    <br>
    <%= f.label :content %>
    <%= f.text_area :content %>
    <%= f.submit %>
<% end %>

app/views/jobs/index.html.erb
<h1><%= index_display_header %></h1>
<% if @jobs.empty? %>

    <h2>No jobs yet. Create a job <%= link_to "here", new_job_path%></h2>

<% else %>
  <%= render partial: "jobs", locals: {jobs: @jobs} %>
<% end %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render partial: "layouts/errors", locals: {object: @job} %>

<!-- render the errors partial, send it the @post as the 'object' -->

<%= form_for(@job) do |f| %>

    <%= f.label "Choose a category:" %>
    <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: true %>

    <p>Or Create a New Category:
    <%= f.fields_for :category do |c| %>
        <%= c.text_field :name %>
    <% end %>
    </p>

    <%= f.label :title %>
    <%= f.text_field :title %>

    <br>
    <%= f.label :company %>
    <%= f.text_field :company %>

    <br>
    <%= f.label :content %>
    <%= f.text_area :content %>

    <br>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <br>
    <%= f.submit "Submit" %>

<% end %>

app/views/jobs/show.html.erb
<h1><%=@job.title%></h1>
<br>
<h2>By: <%=link_to @job.user.username, user_path(@job.user) %> </h2>
<br>
<h2>Company: <%= @job.company%> </h2>
<br>
<h2>Content: <%= @job.content%></h2>
<br>
<h2>Category: <%= @job.category.try(:name) %></h2>
<% if @job.user == current_user %>
    <h3><%= link_to "Edit", edit_job_path(@job) %></h3>
    <h3><%= button_to "Delete", job_path, method:"delete"%></h3>
<% end %>

<p><%= link_to "Add a New Review", new_job_review_path(@job) %></p>

<% if !@job.reviews.empty? %>
    <p><%= link_to "See all Reviews", job_reviews_path(@job) %></p>
    <h3>Reviews:</h3>
    <% @job.reviews.each do |r| %>
        <li><strong><%= r.user.username %></strong> says "<%= link_to r.content, job_review_path(@job, r) %>"</li>
    <% end %>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <style>
      * {
        text-align: center;
        font-family: Georgia, serif;
        color: #000000;
      }
      nav {
        list-style-type: none;
        margin: 0;
        padding: 0;
        overflow: hidden;
        background-color: #000000;
      }
      dt {
        float: left;
      }
      dt a {
        display: block;
        color: white;
        text-align: center;
        padding: 7px 8px;
        text-decoration: none;
      }
      dt a:hover {
        background-color: #696969;
      }
      ul {
	      list-style: none;
      }
  </style>
    <title>JobLister</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>
  <body>
  <br>
    <div>
    <nav>
      <ul>
        <% if logged_in? %>
        <dt><%= link_to "Add a Job", new_job_path %> | </dt>
        <dt><%= link_to "All Jobs", jobs_path %> | </dt>
        <dt><%= link_to "My Jobs", user_jobs_path(current_user) %> | </dt>
        <dt><%= link_to "Add a Review", new_review_path %> | </dt>
        <dt><%= link_to "All Reviews", reviews_path %> | </dt>
        <dt><%= link_to "All Categories", categories_path %> | </dt>
        <dt><%= link_to "Most Active Users", users_most_active_path %></dt>
        <dt><%= link_to "Home", user_path(current_user) %> | </dt>
        <dt><%= button_to "Logout", logout_path, method:"delete" %></dt>

        <% else %>
        <dt><%= link_to "Sign Up", signup_path %> | </dt>
        <dt><%= link_to "Log In", login_path %> | </dt>
        <dt><%= button_to "Log In With Google", '/auth/google_oauth2' %></dt>
        <% end %>
      </ul>
    </nav>
    </div>

    <div>
      <% if flash[:message] %>
        <%= flash[:message] %>
      <% end %>
      <%= @error %>
    </div>

    <%= yield %>
    <div class="wrapper">
      <footer class="branding">
        <small>&copy; 2021 <strong>JobLister</strong></small>
      </footer>
    </div>
  </body>
</html>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render partial: "layouts/errors", locals: {object: @review} %>

<%= form_for(@review) do |f| %>

    <%= f.label :job %>
    <%= f.collection_select :job_id, Job.all, :id, :title %>

    <%= f.label :content %>
    <%= f.text_field :content %>

    <%= f.submit %>

<% end %>

app/views/reviews/index.html.erb
<% if @job %>
    <h1>Reviews for <%= @job.title %></h1>
<% else %>
    <h1>All Reviews</h1>
<% end %>

<ul>
<% @reviews.each do |r| %>
    <li><%= r.user.username %> says "<%= r.content %>" about this post: <strong><%= link_to r.job.title, job_path(r.job_id) %></strong></li>
<% end %>
</ul>

app/views/reviews/new.html.erb
<% if @review.job %>
<h1>New Review for <%= @review.job.title %></h1>
<% else %>
<h1>New Review</h1>
<% end %>

<%= render partial: "layouts/errors", locals: {object: @review} %>

<%= form_for([@review.job, @review]) do |f|%>

  <% if !@review.job %>
    <%= f.label :job %>
    <%= f.collection_select :job_id, Job.all, :id, :title %>
<% else %>
    <%= f.hidden_field :job_id %>
<% end %>

    <%= f.label :content %>
    <%= f.text_field :content %>

    <%= f.submit %>
  
<% end %>

app/views/reviews/show.html.erb
<h2><%= @review.content%> - <%= @review.user.username%></h2>

<% if @review.user == current_user %>
    <%= link_to "Edit Review", edit_review_path(@review) %>
    <h3><%= button_to "Delete", review_path, method:"delete"%></h3>
<% end %>

<h4>Read about the job here: <%= link_to @review.job.title, job_path(@review.job_id) %></h4>

app/views/users/most_active.html.erb
<h1>Most Active Users:</h1>

<div>
 <ul>
   <% @top_users.each do |user| %>
        <li><strong><%= link_to user.username, user_path(user) %></strong></li>
   <% end %>
 </ul>
</div>

app/views/users/new.html.erb
<h1>Signup</h1>

<%= render partial: "layouts/errors", locals: {object: @user} %>

<%= form_for(@user, url: '/signup') do |f| %>

    <%= f.label :username %>
    <%= f.text_field :username %>
    <br>
    <br>
    <%= f.label :email %>
    <%= f.email_field :email, required: true %>
    <br>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
    <br>
    <%= f.submit "Submit" %>

<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.username %></h1>

<%= display_jobs %>